###################################################
#/// Define cluster configuration in this file ///#
###################################################

# How many worker nodes to deploy in addition to the master node
NodeCount: 1



master:
  #####################################################################
  # Set amount of RAM memory,CPU cores and IP address for master node #
  #####################################################################
  memory: 4096
  cpus: 4
  master_ip: "192.168.10.100"
  master_virt: True   # enable nested virtualization on the master node

  ####################################################
  ### set the internal kubernetes pod network CIDR ###
  ####################################################
  pod_network_cidr: "10.244.0.0/16"


worker:
  ###############################################################
  # Set amount of RAM memory and CPU cores for each worker node #
  ###############################################################
  memory: 2048
  cpus: 2
  worker_virt: True      # Enable nested virtualization on worker nodes

 #  Define ip range for worker nodes #
  ip_prefix: "192.168.10."           #
  start_index: 2                     #
  count: <%= @NodeCount %>           #
 # # # # # # # # # # # # # # # # # # #
