###################################################
#/// Define cluster configuration in this file ///#
###################################################

# How many worker nodes to deploy in addition to the master node
NodeCount: 2

master:
  #######################################################################
  # Set the IP, amount of RAM memory, CPU cores and storage drives for master node     #
  #######################################################################
  memory: 4096
  cpus: 4
  master_ip: "192.168.10.100"            # ip of the master node guest VM machine
  additional_storage_drives: 0           # How many additional storage drives the machine should have
  storage_drives_size: 80                # What is the size of each additional storage drive in GB
  master_virt: False                     # Enable/Disable nested virtualization on the master node

  #######################################################################
  #                       set the internal kubernetes pod network CIDR                                       #
  #######################################################################
  pod_network_cidr: "172.16.0.0/16"


worker:
  #######################################################################
  # Set the amount of RAM memory, CPU cores and storage drives for each worker node #
  #######################################################################
  memory: 2048
  cpus: 2
  additional_storage_drives: 0            # How many additional storage drives the machine should have
  storage_drives_size: 80                 # What is the size of each additional storage drive in GB
  worker_virt: False                      # Enable/Disable nested virtualization on worker nodes


  #######################################################################
  #                              Define IP address range for worker nodes                                          #
  #######################################################################
  ip_prefix: "192.168.10."                 # ip prefix for worker nodes
  start_index: 2                           # starting ip address - e.x. 192.168.10.2
  count: <%= @NodeCount %>                 # do not change this line
