###################################################
#/// Define cluster configuration in this file ///#
###################################################

# How many worker nodes to deploy in addition to the master node
NodeCount: 1

master:
  #######################################################################
  # Set the amount of RAM memory, CPU cores and storage drives for  master node         #
  #######################################################################
  memory: 4096
  cpus: 4
  master_ip: "192.168.10.100"
  additional_storage_drives: 2            # How many additional storage drives the machine should have in addition to boot drive
  storage_drives_size: 80                   # What is the size of each storage drive in GB.
  master_virt: False                            # Enable/Disable nested virtualization on the master node

  #######################################################################
  #                       set the internal kubernetes pod network CIDR                                       #
  #######################################################################
  pod_network_cidr: "10.244.0.0/16"


worker:
  #######################################################################
  # Set the amount of RAM memory, CPU cores and storage drives for each worker node #
  #######################################################################
  memory: 2048
  cpus: 2
  additional_storage_drives: 1            # How many additional storage drives the machine should have in addition to boot drive
  storage_drives_size: 80                   # What is the size of each storage drive in GB.
  worker_virt: False                            # Enable/Disable nested virtualization on worker nodes

 #  Define ip range for worker nodes  #
  ip_prefix: "192.168.10."                    #
  start_index: 2                                    #
  count: <%= @NodeCount %>          #
 # # # # # # # # # # # # # # # # # # ###
